mindivateWebsite/views.py
from flask import Blueprint, render_template, request, flash, redirect, url_for, current_app, session, render_template_string
# ... the rest of your imports
from flask_login import login_required, current_user
from .models import EmailUser
from flask_mail import Mail, Message
from . import db, Mail, mail



views = Blueprint('views', __name__)

@views.route('/ebook', methods=['GET', 'POST'])
def ebookPage():
    email = request.form.get('email')
    name = request.form.get('name')
    print(name)


    # if not email:
    #     # flash('No email provided')
    #     return render_template('404.html')

    if email and name:
        existing_user = EmailUser.query.filter_by(email=email).first()
        if existing_user:
            flash('Email already exists.')
            return render_template('ebook.html')
        else:
            new_email_user = EmailUser(email=email, name=name)

            topic = "It is time you finally take action"
                    
            htmlEBOOK = render_template_string("""
<html>
<head>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f4f4f4;
        }
        .container {
            background-color: #ffffff;
            width: 600px;
            margin: 0 auto;
            padding: 20px;
        }
        .message {
            font-size: 16px;
            line-height: 1.6;
            color: #333333;
        }
        .footer {
            font-size: 12px;
            color: #777777;
            margin-top: 20px;
            text-align: center;
        }
        .download-button {
            display: inline-block;
            padding: 10px 15px;
            margin-top: 20px;
            background-color: #007bff;
            color: #ffffff;
            text-decoration: none;
            border-radius: 5px;
        }
    </style>
</head>


<head>
<style>
  body {
    font-family: Arial, sans-serif;
    color: #333;
    line-height: 1.6;
  }

  .email-link {
    color: #3498DB;
    text-decoration: none;
    font-weight: bold;
  }
</style>
</head>
<body>

<p>Hi there {{ name }},</p>

<p>For too long you have procrastinated,</p>

<strong><u><p class="highlight">It is finally time to change that.</p></u></strong>

<p>This ebook is your first step to achieving success.</p>

<p>In addition to that,</p>

<p>You will also receive <strong><u>weekly emails </u></strong> from me.</p>

<p>These emails will be packed with everything I know.</p>

<p>Money. Gym. Masculinity. Discipline.</p>

<p>All of that you get for completely free...</p>


<u><p>This is the <span class="highlight">opportunity of your life,</u></span></p>

<p>If you put in the work,</p>

<p><strong><u><span class="highlight">There is no way for you to fail</span></p> </strong> </u>

  <p><a href="{{ url_for('views.download_ebook', _external=True) }}" class="email-link">👉==Click here to get the ebook==</a>
</p>

<p>Thank you for signing up</p>

<p>-Mindvate</p>

</body>
</html>

""", name=name)
            msg = Message(topic, recipients=[email], html=htmlEBOOK, sender=("Mindivate", "email@mindivate.com"))
            mail.send(msg)
            db.session.add(new_email_user)
            db.session.commit()
            return render_template('gotEbook.html', email=email, name=name)

    return render_template('ebook.html')


@views.errorhandler(404)
def not_found_error(error):
    return render_template('404.html'), 404


@views.route('/test', methods=['GET', 'POST'])
def test():
    return("<h1>test</h1>")



@views.route('/email/ejnfsjf4348f43njfdj94b34j3', methods=['GET', "POST"])

def email():
    # if not current_user.is_authenticated:  # Add this line to check if the user is not logged in
    #     return redirect(url_for('login'))
   
    all_emails = [user.email for user in EmailUser.query.all()]
    all_names = [userName.name for userName in EmailUser.query.all()]
    
    all_users = EmailUser.query.all()

    topic = request.form.get('topic')
    message = request.form.get('message')
    if request.method == 'POST': 

        msg = Message()





#email sending 


        all_users = EmailUser.query.all()
        nameAdd = request.form.get('nameAdd')
        individual_message = ""
        confirm_button = request.form.get('submit')
        test_button = request.form.get('test_submit')

        if True:

            if nameAdd != None:
                    
            
                for user in all_users:
                    all_users = EmailUser.query.all()
                    formatted_message = request.form.get('message')
                    combined_message = f"<p>Hi {user.name}!\n\n</p>{formatted_message}"
                      # Add this line to obtain the formatted text
                    msg.body = f'Hi {user.name}!\n\n{message}'
                    msg = Message(topic, recipients=[user.email], html=combined_message)  # Include the formatted text in the email message
                    
                    message = ("To: " + user.email + "\nDear " + user.name + "\nTOPIC: " + topic + "\n" + message)
                    html_content = """
        <html>
        <head>

        </head>
        <body>

    {{message}}
        </body>
        </html>
        """
                mail.send(msg)
                return redirect('/ebook')
            
                
            else:
                for user in all_users:
                    all_users = EmailUser.query.all()
                    formatted_message = request.form.get('message')  # Add this line to obtain the formatted text
                    msg.body = f'Hi {user.name}!\n\n{message}'
                    
                    msg = Message(topic, recipients=[user.email], html=formatted_message)  # Include the formatted text in the email message
                    
                    message = ("To: " + user.email + "\nDear " + user.name + "\nTOPIC: " + topic + "\n" + message)
                    html_content = """
        <html>
        <head>

        </head>
        <body>

    {{message}}
        </body>
        </html>
        """    
                mail.send(msg)
                return redirect('/sent')     
    
            

        
  

        
    return render_template('email.html', all_emails=all_emails, message=message, all_users=all_users)


@views.route('/file')
def download_file():
    return current_app.send_static_file('demofile2.txt')

@login_required
@views.route('/sent')
def sent():
    return render_template('getEbook.html')




@views.route('/')
def home():
    return redirect('/ebook')

from flask import send_from_directory

@views.route('/download/59853959457')
def download_ebook():
    # Define the directory where your eBooks are stored
    ebook_directory = 'ebook'
    
    # Define the filename based on ebook_id, assuming it's a direct mapping
    # For instance, if ebook_id = '234453', the filename might be 'ebook_234453.pdf'
    ebook_filename = '7_BEST_Productivity_Techniques.pdf'

    # Send file from directory
    return send_from_directory(ebook_directory, ebook_filename, as_attachment=True)

mindivateWebsite/templates/ebook.html
<!DOCTYPE html>
<head>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='logo.png') }}">
   
    <script>
        // Get the modal
        document.addEventListener('DOMContentLoaded', function() {
    // Get the modal
    var modal = document.getElementById("myModal");

    // Get the button that opens the modal
    var btn = document.querySelector(".claim");

    // Get the <span> element that closes the modal
    var span = document.getElementsByClassName("close")[0];

    // When the user clicks the button, open the modal 
    btn.onclick = function() {
      modal.style.display = "flex";
    }

    // When the user clicks on <span> (x), close the modal
    span.onclick = function() {
      modal.style.display = "none";
    }

    // When the user clicks anywhere outside of the modal, close it

});
        </script>

</head>

<body>  
    
    <nav class="navbar">
        <img src="{{ url_for('static', filename='logo.png') }}" class="logo">
    </nav>
 <div class="box">
    <div class="container">
        <h1>Want to get rich?</h1>
        <div class="ebookDiv">
        <img src="{{ url_for('static', filename='ebook.png') }}" class="ebook">
    </div>
        <div class="button">
        <button class="claim">  <h2> CLAIM YOUR FREE EBOOK</h2></button>
    </div>
    </div>
</div>
    <div class="description">
        <h3>
            <p1>
            Break free </p1>from the mundane and discover the secrets to wealth and freedom. 
            
            <br><br>
            This eBook is not just advice, it's a game-changer for anyone eager to escape the rat race and embrace financial success.
            <br><br>
            Ready to unlock your potential and achieve greatness? Dive in now!











        </h3>
    </div>


<!-- The Modal -->
<div id="myModal" class="modal">

    <!-- Modal content -->
    <div class="modal-content">
      <span class="close">&times;</span>
      <form class="modal-form" method="POST" action="{{ url_for('views.ebookPage') }}">
        
        <div class="insInput">

            <div class="name">

        <input type="text" id="name" name="name" required placeholder="Your name:" class="input">
        
    </div>
    <div class="email">
        <input type="email" id="email" name="email" required placeholder="Your email:" class="input">
    </div>
    </div>
<br>
<div class="agree">
        <label for="agree">

            <input type="checkbox" id="agree" name="agree" required cla>
            I agree to receive the e-book and subscribe to email marketing.
          </label>
        </div>
<br>
        <input type="submit" value="SUBMIT" class="submit">
      </form>
    </div>
  
  </div>



</body>

mindivateWebsite/templates/email.html
<!DOCTYPE html>
<head>

    <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- FontAwesome Icons -->
        <link
        rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
      />
      <!-- Google Fonts -->
      <link
        href="https://fonts.googleapis.com/css2?family=Poppins&display=swap"
        rel="stylesheet"
      />
      <!-- Stylesheet -->
      <link rel="stylesheet" href="style.css" />
      <link rel="stylesheet" href="{{ url_for('static', filename='email.css') }}">
      <link rel="stylesheet" href="{{ url_for('static', filename='email.js') }}">


      <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='logo.png') }}">



</head>
<body>

   
  <nav class="navbar">
    <img src="{{ url_for('static', filename='logo.png') }}" class="logo">
</nav>



   
       
        <div class="container">
          <div class="options">
            <!-- Text Format -->
            <button id="bold" class="option-button format">
              <i class="fa-solid fa-bold"></i>
            </button>
            <button id="italic" class="option-button format">
              <i class="fa-solid fa-italic"></i>
            </button>
            <button id="underline" class="option-button format">
              <i class="fa-solid fa-underline"></i>
            </button>
            <button id="strikethrough" class="option-button format">
              <i class="fa-solid fa-strikethrough"></i>
            </button>
            <button id="superscript" class="option-button script">
              <i class="fa-solid fa-superscript"></i>
            </button>
            <button id="subscript" class="option-button script">
              <i class="fa-solid fa-subscript"></i>
            </button>
            <!-- List -->
            <button id="insertOrderedList" class="option-button">
              <div class="fa-solid fa-list-ol"></div>
            </button>
            <button id="insertUnorderedList" class="option-button">
              <i class="fa-solid fa-list"></i>
            </button>
            <!-- Undo/Redo -->
            <button id="undo" class="option-button">
              <i class="fa-solid fa-rotate-left"></i>
            </button>
            <button id="redo" class="option-button">
              <i class="fa-solid fa-rotate-right"></i>
            </button>
            <!-- Link -->
            <button id="createLink" class="adv-option-button">
              <i class="fa fa-link"></i>
            </button>
            <button id="unlink" class="option-button">
              <i class="fa fa-unlink"></i>
            </button>
            <!-- Alignment -->
            <button id="justifyLeft" class="option-button align">
              <i class="fa-solid fa-align-left"></i>
            </button>
            <button id="justifyCenter" class="option-button align">
              <i class="fa-solid fa-align-center"></i>
            </button>
            <button id="justifyRight" class="option-button align">
              <i class="fa-solid fa-align-right"></i>
            </button>
            <button id="justifyFull" class="option-button align">
              <i class="fa-solid fa-align-justify"></i>
            </button>
            <button id="indent" class="option-button spacing">
              <i class="fa-solid fa-indent"></i>
            </button>
            <button id="outdent" class="option-button spacing">
              <i class="fa-solid fa-outdent"></i>
            </button>
            <!-- Headings -->
            <select id="formatBlock" class="adv-option-button">
              <option value="H1">H1</option>
              <option value="H2">H2</option>
              <option value="H3">H3</option>
              <option value="H4">H4</option>
              <option value="H5">H5</option>
              <option value="H6">H6</option>
            </select>
            <!-- Font -->
            <select id="fontName" class="adv-option-button"></select>
            <select id="fontSize" class="adv-option-button"></select>
            <!-- Color -->
            <div class="input-wrapper">
              <input type="color" id="foreColor" class="adv-option-button" />
              <label for="foreColor">Font Color</label>
            </div>
            <div class="input-wrapper">
              <input type="color" id="backColor" class="adv-option-button" />
              <label for="backColor">Highlight Color</label>
            </div>
          </div>
         
    
          <form class="modal-form" method="POST" action="{{ url_for('views.email') }}">
            
            <div class="topicField">
             <input name="topic" id="topic" type="text" placeholder="Topic..." class="topic" autocomplete="off">
            </div>    
             <div class="center-checkbox">
              <input type="checkbox" id="nameAdd" name="nameAdd" class="custom-checkbox-input">
              <label for="nameAdd" class="custom-checkbox-label"><p> Add client's name</p></label>
            </div>
          <div id="text-input" contenteditable="true" name="message">
              
            
        
          </div>
<input type="hidden" id="message" name="message" class="message">
<div class="submitButton">  
      <input type="submit" value="SEND" class="submit" id="sendButton" name="sendButton"> 
          <!-- <input type="submit" value="SEND TEST" class="test_submit"> -->
        </div>
          </form>
        </div> 
      
        
    
        <!--Script-->
        <script src="{{ url_for('static', filename='js/email.js') }}"></script>




    </h3>
           
           



<!-- <div class="p4">
<p4>
    {{individual_message}}



    <br>
    <br>
    HTML: 

    {{htmlMessages|safe}}
    <br>
<br>
  checkbox value:  {{nameAdd}}
</p4>
</div> -->
</body>

mindivateWebsite/templates/emailSent.html
<!DOCTYPE html>
<head>
	<link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='logo.png') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
</head>
<body>
    <div class="description">
        <h3>
            <p1>
            Emails </p1>were sent.
            






        </h3>
    </div>


</body>

mindivateWebsite/templates/gotEbook.html
<!DOCTYPE html>
<head>
	<link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='logo.png') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
</head>
<body>
    <div class="description">
        <h3>
            <p1>
            Thanks </p1>for downloading our ebook!
            






        </h3>
    </div>


</body>

mindivateWebsite/templates/login.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Mindivate</title>
	<link rel="stylesheet" href="{{ url_for('static', filename='login.css') }}">
<script
    type="text/javascript"
   src="{{ url_for('static', filename='main.js') }}"
>


</script>   

<link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='logo.png') }}">
</head>
<body>

    <nav class="navbar">
        <img src="{{ url_for('static', filename='logo.png') }}" class="logo">
    </nav>

<div class="login-form">

<form class="modal-form" method="POST" action="{{ url_for('auth.loginPage') }}">
       

        
        <input type="text" placeholder="Email" id="email" name="email">

       
        <input type="password" placeholder="Password" id="password" name="password">

        

        <button type="submit" class="logIn">Log In</button>


        <div class="line"></div>

        

      


  
    </form>
</div>



</body>
</html>